source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Luncheon_Example' do
  pod "Luncheon", path: "../"
end

target 'Luncheon_Tests' do
  pod "Luncheon", path: "../"

  pod 'Quick'
  pod 'Nimble'
  pod 'Nocilla'
end
