source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Luncheon_Example', exclusive: true do
  pod 'Placemat', '~> 0.1'
  pod 'Alamofire', git: "git@github.com:Alamofire/Alamofire.git", branch: "swift-2.0"
  pod "Luncheon", path: "../"
end

target 'Luncheon_Tests', exclusive: true do
  pod "Luncheon", path: "../"

  pod 'Quick', '~> 0.4'
  pod 'Nimble', '2.0.0-rc.1'
  pod 'Nocilla'
end
